<a href="https://colab.research.google.com/github/RutujaBidkar/Python_Workshop/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
numbers = pd.Series([10,20,30,40,50])
numbers

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
data =(100,200,300)
s = pd.Series(data)
s

0    100
1    200
2    300
dtype: int64

In [8]:
Student_Name = {
    "Maths" :90,
    "English" : 80,
    "Marathi": 95
}
s = pd.Series(Student_Name)
s

Maths      90
English    80
Marathi    95
dtype: int64

In [9]:
print(s)

Maths      90
English    80
Marathi    95
dtype: int64

In [11]:
sales = pd.Series(
    [5000, 7000, 9000],
    index=["Jan", "Feb", "March"]
)

print(sales)

Jan      5000
Feb      7000
March    9000
dtype: int64

In [13]:
marks = pd.Series([80,90,80])
print(marks[0])

80

In [16]:
sales = pd.Series (
    [80,70,90],
    index = ["Jan","Feb","Mar"]
)
print(sales["Feb"])

70