<a href="https://colab.research.google.com/github/RutujaBidkar/Python_Workshop/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import pandas
import pandas as pd

In [2]:
#Creates pandas series
data = [10,20,30,40,50]

In [4]:
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
#Create a Series with Custom Index
s = pd.Series(
    [80,90,85],
index = ["Maths","Physics","chemistry"]
)
print(s)

Maths        80
Physics      90
chemistry    85
dtype: int64

In [9]:
#Create a DataFrame
data = {
    "Name" : ["Rutuja" ,"Kunal","kunalvis"],
    " age" : [23,25,30],
    "Salary": [500000,450000,480000]

    }

df = pd.DataFrame(data)
print(df)

       Name   age  Salary
0    Rutuja    23  500000
1     Kunal    25  450000
2  kunalvis    30  480000

In [10]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [11]:
data = [10,20,30,40,50]
data

[10, 20, 30, 40, 50]

In [13]:
#Create a Series with custom indexes:
r = pd.Series (
    [70,80,90],
index = ["Pyhsics","Maths","chemistry"]
)
r

Pyhsics      70
Maths        80
chemistry    90
dtype: int64

In [15]:
#Create a DataFrame with these columns:
data = {
    "Name" : ["Rutuja", "Pallavi", "Rutu"],
    "Age"  : [23,24,23],
    "City" :["Pune","Kholapur","Solapur"]

}
df = pd.DataFrame(data)
df

      Name  Age      City
0   Rutuja   23      Pune
1  Pallavi   24  Kholapur
2     Rutu   23   Solapur